#!/system/bin/sh

# Yocdroid su portability wrapper.  Different Android distros ship
# incompatible "su" variants.

# First find it.  Don't trust PATH.
SU=/system/xbin/su
for d in `echo $PATH | sed 's/:/ /g'` /sbin /vendor/bin /system/sbin /system/bin; do
    if [ -x "$d/su" ]; then
	SU=$d/su
    fi
done

if [ -x "$d/su" ]; then
    echo Cannot find a working su >&2
fi

if grep -q 'com\.noshufou\.android\.su' $SU; then
   # This su, which works with the Superuser.apk tool, is distributed
   # with Cyanogenmod (and may others), is popular in the "mod"
   # community, and supports a traditional Unix su syntax.
   exec $SU -c "$@"
else
   # Google's AOSP su is non-standard, but installed by default on
   # "real" development images.
   exec $SU "$@"
fi
