#!/system/bin/sh

# Bring up a Yocto chroot on Android
#
# This bootstrap shell script is designed to run using only the
# Android toolbox environment.

D=/data/y
CGDIR=/dev/yocdroid-cgroup
CGTASKS=$CGDIR/yocdroid/tasks

# Make a cgroup hierarchy for yocdroid processes
mkdir -p $CGDIR
mount -t cgroup -o none,name=yocdroid cgroup $CGDIR
mkdir -p $CGDIR/yocdroid

# Add our own pid to that cgroup so persistent tasks we spawn
# (e.g. yocdroid-mountd) get killed appropriately at stop time.
echo $$ > $CGTASKS

# Initialize the bind mounts, then spawn the daemon to maintain it
$D/sbin/yocdroid-mountall
$D/sbin/yocdroid-mountd $D/sbin/yocdroid-mountall

# Presumptive bug (or a feature I don't understand) workaround: do
# /data last because bind mounting something inside a directory that
# has already been bind mounted actually doubles the depth.  That is,
# if "/data/y/data" is already a bind mount to "/data", then mounting
# "/data/y/acct" actually puts the mount under "/data/y/data/y/acct"
mkdir -p $D/data
mount -o bind /data $D/data
